server:
  port: 8080
spring:
  datasource:
    name: blogsql
    url: jdbc:mysql://127.0.0.1:3306/myblog?serverTimezone=Asia/Shanghai
    username: root
    password: 199210
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    suffix: .ftl
    template-loader-path: classpath:/templates
mybatis:
  type-aliases-package: com.ydm.blog.entity
  mapper-locations: classpath*:mapper/*.xml
